name: Deploy on EC2 - Stable
### EDIT ssh -o to send AUTH_ENABLED, HOST_FQDN, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
### YOU HAVE TO CONFIGURE ssh agent ON SERVER TO ACCEPT THESE
### YOU HAVE TO SET GITHUB ENV VARS AS WELL
on:
  release:
    types:
      - published

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{secrets.AWS_PRIVATE_KEY_STABLE}}
            HOSTNAME : ${{secrets.HOSTNAME_STABLE}}
            USERNAME : ${{secrets.USERNAME}}
            HOST_FQDN: ${{secrets.STABLE_HOST_FQDN}}
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -o SendEnv=AUTH_ENABLED -o SendEnv=HOST_FQDN -o SendEnv=AWS_ACCESS_KEY_ID -o SendEnv=AWS_SECRET_ACCESS_KEY -i private_key ${USERNAME}@${HOSTNAME} '
            cd /home/ubuntu/opencdms-api
            git pull origin main
            docker-compose -f docker-compose.prod.yml down -v --remove-orphans
            docker-compose -f docker-compose.prod.yml up -d --build
            docker-compose -f docker-compose.prod.yml stop opencdms-api
            sleep 30
            docker-compose -f docker-compose.prod.yml up -d --build
          '